services:
  tutorial:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tutorial-app
    restart: unless-stopped
    volumes:
      - ./tutorial:/var/www/app
    ports:
      - "8000:8000"
    networks:
      - tutorial_net

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./tutorial:/var/www/app
      - ./certbot/www/:/var/www/certbot/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - tutorial
    networks:
      - tutorial_net

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - tutorial_net

networks:
  tutorial_net:
    driver: bridge
